---
- name: Config Web VM with Docker
  hosts: elkservers
  become: true
  tasks:
    - name: Install docker
      command: 'sysctl -w vm.max_map_count=262144'

    - name: Install docker
      apt:
        name: docker.io
        state: present

    - name: Install pip
      apt:
        name: python-pip
        state: present

    - name: Install pip-docker
      pip:
        name: docker
        state: present

    - name: download and launch a docker web container
      docker_container:
        name: dvwa
        image: sebp/elk
        state: started
        published_ports:
          - '5601:5601'
          - '9200:9200'
          - '5044:5044'
